#!/bin/bash

echo 'Syncing files to server'
rsync --exclude=node_modules/ -rave "ssh -i ~/.ssh/qnzl -A" * root@8.9.3.221:graph;

echo 'SSHing in and restarting the server'
ssh root@8.9.3.221 -i ~/.ssh/qnzl "cd graph && npm install && sudo supervisorctl restart graph"

