#!/bin/bash

rsync -rave "ssh -i ~/.ssh/qnzl" infra/graph.conf root@8.9.3.221:/etc/supervisor/conf.d;

rsync -rave "ssh -i ~/.ssh/qnzl" infra/graph root@8.9.3.221:/etc/nginx/sites-available;

ssh root@8.9.3.221 -i ~/.ssh/qnzl "ln -s /etc/nginx/sites-available/graph /etc/nginx/sites-enabled/ && sudo service nginx reload && sudo service nginx restart && sudo supervisorctl reload && sudo supervisorctl restart graph && certbot --nginx"


